### ISSUE TITLE
404 error when sending no arguments

### ISSUE THREAD

**Issue by jacksonmelcher** [jacksonmelcher/rc-reminder-bot#9]
For some reason I am getting this error when I only mention the bot (`@remind`). It is not registering as a 404 error on the RingCentral dashboard so it might be a problem with ringcentral.js.

```
(node:18432) UnhandledPromiseRejectionWarning: Error: status: 404
statusText: Not Found
data: {
  "message": "Not Found"
}
config: {
  "url": "https://platform.devtest.ringcentral.com/restapi/v1.0/glip/groups/undefined/posts",
  "method": "post",
  "data": "{\"attachments\":[{\"type\":\"Card\",\"text\":\"**undefined**\",\"footnote\":{\"text\":\"Reminder created by undefined\"}}]}",
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "Content-Type": "application/json;charset=utf-8",
    "Authorization": "Bearer U0pDMTJQMDFQQVMwMHxBQUMyOGtNMEYzMFg2VmRxc3hwVDFmTElneG0xTmx4ZXpYb0owa1lrNTNuM0xoVkFfMmo0LXN5UXVmeGdZT2FQOWdwNF9QWWRPMEVYNENYQjd4dmJsWHJoOU1pQ0tjQmZFWE04RWFEc3FFZ0lVQUJnbmFtelhsTjJWcG5ITWlHbWlRWnlSVUdSUHlBeW13NVU4YkptV2hHamxZWkluRE9pbHNncTBhUE9fYmRscS11RkNEb0ZRc1B2MGNxTTYzb2d5ZWZaUlgyaXBHYXhsVm9VZkl3QnE3RzZ8U2k0dFZBfGlFWGpleGxfa0FhNTEtSzVNbWlHUUF8QUE",
    "X-User-Agent": "tylerlong/ringcentral-js-concise",
    "RC-User-Agent": "tylerlong/ringcentral-js-concise",
    "User-Agent": "axios/0.19.2",
    "Content-Length": 108
  },
  "transformRequest": [
    null
  ],
  "transformResponse": [
    null
  ],
  "timeout": 0,
  "xsrfCookieName": "XSRF-TOKEN",
  "xsrfHeaderName": "X-XSRF-TOKEN",
  "maxContentLength": -1
}
    at Function._axios.request (/Users/jackson.melcher/Development/glip-announcements/node_modules/ringcentral-js-concise/dist/webpack:/RingCentral/src/ringcentral.js:58:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:18432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jacksonmelcher** [comment]
Fixed with new database integration.
